metadata:
  annotations:
    kubernetes.io/change-cause: {{ .ChangeCause }}
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/created-by: {{ .CreatedBy }}
    spec:
      containers:
      - name: {{ .Container }}
        image: {{ .Image }}
        imagePullPolicy: Always
        command:
        args:
        livenessProbe: ~
        readinessProbe: ~
        startupProbe: ~
        volumeMounts:
          - name: patch-configmap
            mountPath: {{ .ConfigMapMount }}
          {{ range $i, $mount := .Mounts }}
          - name: "patch-mount-{{ $i }}"
            mountPath: {{ $mount.MountPath }}
          {{ end }}
      volumes:
        - name: patch-configmap
          configMap:
            name: {{ .Deployment }}-patch
        {{ range $i, $mount := .Mounts }}
        - name: "patch-mount-{{ $i }}"
          hostPath:
            path: {{ $mount.HostPath }}
        {{ end }}