// Code generated by go-bindata. DO NOT EDIT.
// sources:
// the-hook/Dockerfile (167B)
// the-hook/deployment-patch.yaml (761B)

package bindata

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _theHookDockerfile = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x24\xca\xb1\x6e\x83\x30\x10\x80\xe1\xdd\x4f\x71\xb5\x3a\xd6\x35\x52\xa5\x0e\x45\x1d\x18\x08\x62\x00\x22\x8b\x0c\x51\x94\x01\xec\xd3\x19\xc9\x70\x08\x0c\x79\xfd\x88\x64\xf9\x96\xff\xcf\x4c\x01\x65\x95\x15\xf9\x3f\x71\xe8\x26\xfa\x0b\x5d\xc4\x35\x8a\x93\x69\x2a\xf8\x7c\x15\x21\xcc\xa5\x06\x62\x20\x8c\x40\x43\xf4\x5b\xff\x6d\x79\xd4\xc4\xca\x61\xd8\x51\xbf\xb5\xa3\xd3\x2e\xec\x42\xe4\x75\x6b\xae\xe7\xa6\xac\x5b\xb8\x49\xdd\x0f\x93\x5e\xbd\xfc\x02\xa9\xec\xe1\xc3\x0f\x01\x21\x2e\x1b\xa6\xe0\x18\xd0\x7a\x06\x62\x45\x4b\x37\xcf\x01\x15\xf1\x47\x0a\x6b\x40\x9c\xe1\xe7\x37\x49\x8e\x67\x42\x79\x7f\x06\x00\x00\xff\xff\xee\xc6\x23\xf3\xa7\x00\x00\x00")

func theHookDockerfileBytes() ([]byte, error) {
	return bindataRead(
		_theHookDockerfile,
		"the-hook/Dockerfile",
	)
}

func theHookDockerfile() (*asset, error) {
	bytes, err := theHookDockerfileBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "the-hook/Dockerfile", size: 167, mode: os.FileMode(0644), modTime: time.Unix(1633940824, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x18, 0x2, 0xa4, 0x80, 0xee, 0xd7, 0xf2, 0x95, 0x86, 0x3b, 0x54, 0xd8, 0xe4, 0x7a, 0x6b, 0x60, 0xee, 0x69, 0x95, 0x29, 0xe2, 0x7a, 0xed, 0x33, 0x25, 0x75, 0x8, 0xa, 0x62, 0xf5, 0x6, 0xe4}}
	return a, nil
}

var _theHookDeploymentPatchYaml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x51\xcb\x6a\xc4\x30\x0c\xbc\xef\x57\x88\x90\x63\xb3\x1f\x10\xe8\xa9\x3d\xb4\xd0\x85\xfd\x05\xad\xa3\x4d\x0c\x96\x6d\x1c\x67\xa1\x04\xff\x7b\xb1\xbd\x49\x9c\xb6\xf4\x91\x93\x35\x92\x46\x33\x93\xc3\x68\x49\xb4\x07\x00\x4f\x6c\x15\x7a\x8a\x6f\x00\x26\x8f\x1d\x7a\xcc\x15\x80\xc2\x0b\xa9\x71\xa9\x00\xe6\x19\x8e\x6f\x11\x83\x10\x5a\xa8\xbc\x9b\xa8\x4a\xcd\x85\x2e\x7e\xc2\x68\x8f\x52\x93\x5b\x17\x1b\xd0\xc8\xd4\xa6\xf5\xa7\xa5\x0b\x21\xac\xbc\x92\xb1\xbf\xf7\x5f\xe3\xb3\xec\x09\xc3\x8c\xba\xdb\x44\xa0\xeb\x0b\x49\x4a\xde\x48\xd3\x38\x9e\x9d\xb9\xd0\x06\x3b\xc2\x4e\x7e\x83\xdf\x8c\x9a\x98\x4e\x66\xd2\xbe\x20\xd9\x24\x5a\xf4\x62\x68\x84\xd1\x57\xd9\x33\xda\x62\x02\x80\xe3\xd6\x19\xfd\xb0\x3a\xb9\xca\xfe\x84\x36\xb1\x95\x92\x53\x50\x0e\x75\x4f\x50\xcb\x07\xa8\xd3\x22\xb4\x8f\x70\xcc\x87\xf7\xb3\xcb\xe9\x2a\xdf\x4e\xc3\xcd\x3c\x43\x2d\x21\x84\xea\x07\x05\x99\x37\x73\x46\xf0\x8b\x04\xd2\xdd\x86\x65\xe7\x85\xe9\xdf\x2d\x8b\xc5\x61\xbb\x53\xb1\xfd\xcc\x67\xb2\xca\xbc\x33\x25\xfb\x4d\x22\x3a\xfc\x3f\x82\x3f\x07\x30\x98\x31\xbb\xdf\xc9\xb1\x9f\xf2\x78\xb9\x4f\x95\x27\xd6\x30\x3e\x02\x00\x00\xff\xff\x35\x64\xfd\xe0\xf9\x02\x00\x00")

func theHookDeploymentPatchYamlBytes() ([]byte, error) {
	return bindataRead(
		_theHookDeploymentPatchYaml,
		"the-hook/deployment-patch.yaml",
	)
}

func theHookDeploymentPatchYaml() (*asset, error) {
	bytes, err := theHookDeploymentPatchYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "the-hook/deployment-patch.yaml", size: 761, mode: os.FileMode(0644), modTime: time.Unix(1633985411, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe1, 0xac, 0xc7, 0x3d, 0xd, 0xa1, 0x56, 0x95, 0xe1, 0xe2, 0xd7, 0x7e, 0x7b, 0xd9, 0x58, 0x20, 0xcd, 0xc0, 0x74, 0x1a, 0xe2, 0x88, 0xf, 0x87, 0xd0, 0x16, 0x32, 0x13, 0x80, 0x39, 0x89, 0xd4}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"the-hook/Dockerfile":            theHookDockerfile,
	"the-hook/deployment-patch.yaml": theHookDeploymentPatchYaml,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"the-hook": {nil, map[string]*bintree{
		"Dockerfile": {theHookDockerfile, map[string]*bintree{}},
		"deployment-patch.yaml": {theHookDeploymentPatchYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
